add in some std

diff --git a/fam b/fam
--- a/fam
+++ b/fam
@@ -39,8 +39,8 @@ elif [ "$test" = "1" ] || [ "$fasttest" = "1" ] || [ "$coverage" = "1" ]; then
                 -o bin/test_fam \
                 -L .obj \
                 -l static=test \
-                -l static=secp256k1 -l \
-                static=gmp ${rustflags} ||  exit 1;
+                -l static=secp256k1 \
+		-l static=gmp ${rustflags} ||  exit 1;
         ./bin/test_fam ${filter} --test-threads=1 || exit 1;
         if [ "$coverage" = "1" ]; then
                 git log -1 > /tmp/coverage.txt || exit 1;
@@ -63,15 +63,18 @@ elif [ "$all" = "1" ]; then
 	done
 	cd ..
 	if [ "$usemrustc" = "1" ]; then
-		echo "${mrustc} --crate-type=lib rust/mod.rs -L${output} --cfg mrustc -o .obj/rust.o -C panic=abort";
+		echo "${mrustc} --crate-type=lib rust/mod.rs -L${output} --cfg mrustc -o .obj/rust.o -C panic=abort -l static=test -l static=secp256k1 -l static=gmp";
 		${mrustc} \
 			-O --crate-type=lib \
 			rust/mod.rs -L${output} \
 			--cfg mrustc \
 			-o .obj/rust \
+			-l static=test -l \
+			static=secp256k1 \
+			-l static=gmp \
 			-C panic=abort || exit 1;
 	else
-		echo "rustc +nightly -C panic=abort -C opt-level=3 --emit=obj --crate-type=lib -o .obj/rust.o rust/mod.rs";
+		echo "rustc +nightly -C panic=abort -C opt-level=3 --emit=obj --crate-type=lib -o .obj/rust.o -l static=test -l static=secp256k1 -l static=gmp rust/mod.rs";
 		rustc +nightly \
 			${debug} -C \
 			panic=abort -C \
@@ -79,6 +82,9 @@ elif [ "$all" = "1" ]; then
 			--emit=obj \
 			--crate-type=lib \
 			-o .obj/rust.o \
+			-l static=test \
+                	-l static=secp256k1 \
+                	-l static=gmp \
 			rust/mod.rs || exit 1;
 	fi
 	echo "${cc} ${ccflags} -o bin/fam .obj/*.o -L.obj -lsecp256k1";
